spring.profiles.active: "local"

service:
  onlineStatusTimeout: 5m

  serviceUserCache:
    expirationTime: 5m
    size: 100_000

  userDetailsCache:
    expirationTime: 2m
    size: 100_000

server:
  servlet:
    context-path: "/v1/api"
  port: 8080

# Spring
spring:
  h2:
    console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    platform: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

# Logging
logging:
  pattern.console: "%-5level %logger{36} - %msg%n"
  level:
    ru.protei: INFO
    org.springframework: ERROR
    root: ERROR
  path: 'user-service'
  pattern.file: "%-5level %logger{36} - %msg%n"